openapi: 3.0.3
info:
  title: Advanced Todo Chatbot API
  description: API for advanced todo management with AI chatbot, event-driven architecture, and Dapr integration
  version: 1.0.0
servers:
  - url: https://api.todo-chatbot.com/v1
    description: Production server
  - url: https://staging.todo-chatbot.com/v1
    description: Staging server

paths:
  /tasks:
    get:
      summary: Get all tasks for the authenticated user
      description: Retrieve a list of tasks with optional filtering, sorting, and pagination
      parameters:
        - name: completed
          in: query
          description: Filter by completion status (true/false)
          required: false
          schema:
            type: boolean
        - name: priority
          in: query
          description: Filter by priority (low, medium, high)
          required: false
          schema:
            type: string
            enum: [low, medium, high]
        - name: tag
          in: query
          description: Filter by tag
          required: false
          schema:
            type: string
        - name: sort_by
          in: query
          description: Sort by field (created_at, updated_at, due_date, priority, title)
          required: false
          schema:
            type: string
            enum: [created_at, updated_at, due_date, priority, title]
        - name: order
          in: query
          description: Sort order (asc, desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: search
          in: query
          description: Search tasks by keyword in title or description
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new task
      description: Create a new task with advanced features like priority, tags, due date, and recurrence
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  maxLength: 255
                description:
                  type: string
                completed:
                  type: boolean
                  default: false
                due_date:
                  type: string
                  format: date-time
                priority:
                  type: string
                  enum: [low, medium, high]
                  default: medium
                tags:
                  type: array
                  items:
                    type: string
                recurrence_pattern:
                  $ref: '#/components/schemas/RecurrencePattern'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{taskId}:
    get:
      summary: Get a specific task
      description: Retrieve a single task by its ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a task
      description: Update an existing task with new information
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 255
                description:
                  type: string
                completed:
                  type: boolean
                due_date:
                  type: string
                  format: date-time
                priority:
                  type: string
                  enum: [low, medium, high]
                tags:
                  type: array
                  items:
                    type: string
                recurrence_pattern:
                  $ref: '#/components/schemas/RecurrencePattern'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a task
      description: Permanently delete a task by its ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /chat/conversation:
    post:
      summary: Process a chat message
      description: Send a message to the AI chatbot and receive a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                conversation_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Chat response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  action:
                    type: string
                    enum: [todo_created, todo_updated, todo_completed, todo_deleted, info_retrieval]
                  task_data:
                    $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reminders:
    get:
      summary: Get all reminders for the authenticated user
      description: Retrieve a list of reminders with optional filtering
      parameters:
        - name: status
          in: query
          description: Filter by reminder status (pending, sent, failed)
          required: false
          schema:
            type: string
            enum: [pending, sent, failed]
        - name: task_id
          in: query
          description: Filter by task ID
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of reminders
          content:
            application/json:
              schema:
                type: object
                properties:
                  reminders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reminder'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /events:
    get:
      summary: Get events
      description: Retrieve a list of events with optional filtering
      parameters:
        - name: event_type
          in: query
          description: Filter by event type
          required: false
          schema:
            type: string
        - name: processed_status
          in: query
          description: Filter by processing status
          required: false
          schema:
            type: string
            enum: [pending, processing, processed, failed]
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 255
        description:
          type: string
        completed:
          type: boolean
        due_date:
          type: string
          format: date-time
        priority:
          type: string
          enum: [low, medium, high]
        tags:
          type: array
          items:
            type: string
        recurrence_pattern:
          $ref: '#/components/schemas/RecurrencePattern'
        user_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        next_occurrence_date:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed
        - priority
        - user_id
        - created_at
        - updated_at

    RecurrencePattern:
      type: object
      properties:
        frequency:
          type: string
          enum: [daily, weekly, monthly, yearly]
        interval:
          type: integer
          minimum: 1
          default: 1
        end_condition:
          type: object
          properties:
            type:
              type: string
              enum: [after_occurrences, on_date]
            value:
              type: string
              format: date-time
        days_of_week:
          type: array
          items:
            type: string
            enum: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
          description: Days of week for weekly recurrences

    Reminder:
      type: object
      properties:
        id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        scheduled_time:
          type: string
          format: date-time
        sent_status:
          type: string
          enum: [pending, sent, failed]
        delivery_attempts:
          type: integer
        last_attempt_time:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - task_id
        - scheduled_time
        - sent_status
        - created_at

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        event_type:
          type: string
        payload:
          type: object
        source:
          type: string
        correlation_id:
          type: string
          format: uuid
        processed_status:
          type: string
          enum: [pending, processing, processed, failed]
        created_at:
          type: string
          format: date-time
        processed_at:
          type: string
          format: date-time
      required:
        - id
        - event_type
        - payload
        - source
        - created_at

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        total_pages:
          type: integer

    Error:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string

security:
  - bearerAuth: []

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT