openapi: 3.0.0
info:
  title: MCP Todo Tools API
  description: Model Context Protocol tools for AI agents to manage todos
  version: 1.0.0
paths:
  /tools/create_todo:
    post:
      summary: Create a new todo
      description: Allows AI agents to create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the todo
                  example: "Buy groceries"
                description:
                  type: string
                  description: Optional description of the todo
                  example: "Milk, eggs, bread"
                due_date:
                  type: string
                  format: date-time
                  description: Optional due date for the todo
                  example: "2025-01-15T10:00:00Z"
                priority:
                  type: string
                  enum: [low, medium, high, urgent]
                  description: Priority of the todo
                  default: "medium"
              required:
                - title
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /tools/get_todos:
    get:
      summary: Get all todos for the user
      description: Allows AI agents to retrieve all todos for the authenticated user
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

  /tools/get_todo:
    get:
      summary: Get a specific todo
      description: Allows AI agents to retrieve a specific todo by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The requested todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /tools/update_todo:
    put:
      summary: Update a todo
      description: Allows AI agents to update an existing todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: The ID of the todo to update
                title:
                  type: string
                  description: The updated title of the todo
                  example: "Buy groceries and cook dinner"
                description:
                  type: string
                  description: The updated description of the todo
                  example: "Milk, eggs, bread, and ingredients for dinner"
                status:
                  type: string
                  enum: [pending, in_progress, completed, cancelled]
                  description: The updated status of the todo
                due_date:
                  type: string
                  format: date-time
                  description: The updated due date for the todo
                  example: "2025-01-16T10:00:00Z"
                priority:
                  type: string
                  enum: [low, medium, high, urgent]
                  description: The updated priority of the todo
              required:
                - id
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /tools/delete_todo:
    delete:
      summary: Delete a todo
      description: Allows AI agents to delete a specific todo by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Todo deleted successfully
        '404':
          $ref: '#/components/responses/NotFoundError'

  /tools/search_todos:
    post:
      summary: Search todos by criteria
      description: Allows AI agents to search todos by various criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Search for todos with this title
                status:
                  type: string
                  enum: [pending, in_progress, completed, cancelled]
                  description: Filter todos by status
                due_date_from:
                  type: string
                  format: date-time
                  description: Filter todos with due date on or after this date
                due_date_to:
                  type: string
                  format: date-time
                  description: Filter todos with due date on or before this date
                priority:
                  type: string
                  enum: [low, medium, high, urgent]
                  description: Filter todos by priority
      responses:
        '200':
          description: A list of matching todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        status:
          type: string
          enum: [pending, in_progress, completed, cancelled]
          example: "pending"
        due_date:
          type: string
          format: date-time
          example: "2025-01-15T10:00:00Z"
        priority:
          type: string
          enum: [low, medium, high, urgent]
          example: "medium"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user_id:
          type: string
          format: uuid
      required:
        - id
        - title
        - status
        - priority
        - created_at
        - updated_at
        - user_id

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Bad request"
        message:
          type: string
          example: "Invalid input data"

  responses:
    BadRequestError:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'