openapi: 3.0.0
info:
  title: Todo Management API
  description: API for managing todos through the AI chatbot interface
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/todos:
    get:
      summary: Get all todos for the authenticated user
      description: Retrieve a list of all todos for the current user
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Create a new todo
      description: Create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/todos/{id}:
    get:
      summary: Get a specific todo
      description: Retrieve a specific todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The requested todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    put:
      summary: Update a todo
      description: Update an existing todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    delete:
      summary: Delete a todo
      description: Delete a specific todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/conversations:
    post:
      summary: Create a new conversation
      description: Initialize a new conversation with the AI chatbot
      responses:
        '201':
          description: Conversation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/conversations/{id}/messages:
    post:
      summary: Send a message in a conversation
      description: Send a message to the AI chatbot in a specific conversation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        status:
          type: string
          enum: [pending, in_progress, completed, cancelled]
          example: "pending"
        due_date:
          type: string
          format: date-time
          example: "2025-01-15T10:00:00Z"
        priority:
          type: string
          enum: [low, medium, high, urgent]
          example: "medium"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user_id:
          type: string
          format: uuid
      required:
        - id
        - title
        - status
        - priority
        - created_at
        - updated_at
        - user_id

    CreateTodoRequest:
      type: object
      properties:
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        due_date:
          type: string
          format: date-time
          example: "2025-01-15T10:00:00Z"
        priority:
          type: string
          enum: [low, medium, high, urgent]
          default: "medium"
      required:
        - title

    UpdateTodoRequest:
      type: object
      properties:
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        status:
          type: string
          enum: [pending, in_progress, completed, cancelled]
        due_date:
          type: string
          format: date-time
          example: "2025-01-15T10:00:00Z"
        priority:
          type: string
          enum: [low, medium, high, urgent]

    Conversation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        started_at:
          type: string
          format: date-time
        last_interaction_at:
          type: string
          format: date-time
        context_data:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - started_at
        - created_at
        - updated_at

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        conversation_id:
          type: string
          format: uuid
        sender_type:
          type: string
          enum: [user, ai]
        content:
          type: string
          example: "Add a task to buy groceries"
        timestamp:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - conversation_id
        - sender_type
        - content
        - timestamp
        - created_at

    SendMessageRequest:
      type: object
      properties:
        content:
          type: string
          example: "Add a task to buy groceries"
      required:
        - content

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Bad request"
        message:
          type: string
          example: "Invalid input data"

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequestError:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'