apiVersion: v1
kind: Secret
metadata:
  name: acr-image-pull-secret
  namespace: todo-app
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0b2RvYXBwcmVnaXN0cnkyMDI2LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJ0b2RvYXBwcmVnaXN0cnkyMDI2IiwicGFzc3dvcmQiOiJMQ2M2N3djWjh6cW44UlZmOEVpWm5IN0hoWkhtNEozbmNtdUY1cHYzTmVUQ1ROQndxenBhSlFRSjk5Q0JBQ1llQmpGRXFnN05BQUFDQVpDUmdqeG4iLCJhdXRoIjoiZEc5a2IyRndjSEpsWjJsemRISjVNakF5TmpwTVEyTTJOM2RqV2poNmNXNDRVbFptT0VWcFdtNUlOMGhvV2todE5Fb3pibU50ZFVZMWNIWXpUbVZVUTFST1FuZHhlbkJoU2xGUlNqazVRMEpCUTFsbFFtcEdSWEZuTjA1QlFVRkRRVnBEVW1kcWVHND0ifX19
type: kubernetes.io/dockerconfigjson